# Generated by Django 4.2 on 2023-05-23 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companie',
            old_name='created_at',
            new_name='created_by',
        ),
    ]
